import builtins
from typing import Any, Protocol


class MetadataRepositoryProtocol(Protocol):
    def create(self, document: dict[str, Any]) -> dict[str, Any]: ...

    def update(self, metadata_id: str, data: dict[str, Any]) -> dict[str, Any] | None: ...

    def create_history_entry(self, document: dict[str, Any]) -> dict[str, Any]: ...

    def delete(self, metadata_id: str) -> bool: ...
    def get_by_id(self, metadata_id: str) -> dict[str, Any] | None: ...

    def get_by_data_asset_key(self, data_asset_key: str) -> dict[str, Any] | None: ...

    def list(
        self, filters: dict[str, Any] | None = None, skip: int = 0, limit: int | None = None
    ) -> builtins.list[dict[str, Any]]: ...

    def count(self, filters: dict[str, Any] | None = None) -> int: ...

    def list_history(self, metadata_id: str) -> builtins.list[dict[str, Any]]: ...

    def list_all_history(self) -> builtins.list[dict[str, Any]]: ...
